"""Prompt and response templates for training (SFT + GRPO).

These mirror :mod:`src.utils.prompts` but are split into a *prompt* (user
turn) and a *response* (assistant turn), since SFT requires both halves and
GRPO requires only the prompt half.

Three SFT modes are supported, controlled by ``sft_mode``:

  * ``label``   — assistant emits only ``<decision>`` (no ``<analysis>``).
  * ``teacher`` — assistant emits ``<analysis>`` + ``<decision>``, where the
                  analysis was generated by a larger teacher model.
  * ``self``    — same shape as ``teacher``, but the analysis was self-
                  generated by the target model.

The ``teacher`` and ``self`` modes share the same prompt/response shape;
they differ only in where the ``analysis`` text comes from in the dataset.
"""

# ---------------------------------------------------------------------------
# Prompt building blocks
# ---------------------------------------------------------------------------

_OUTPUT_FORMAT_LABEL_ONLY = """
# Output Format
<decision>
SELF_SOLVE or DELEGATE
</decision>
""".strip()

_OUTPUT_FORMAT_WITH_ANALYSIS = """
# Output Format
<analysis>
Explain why you chose SELF_SOLVE or DELEGATE.
</analysis>

<decision>
SELF_SOLVE or DELEGATE
</decision>
""".strip()

_QUERY_MATH = """
# Query:
{query}
""".strip()

_QUERY_SCIENCE = """
# Query:
Question: {question}
Choices:
{choices}
""".strip()

_PROMPT_BODY = """
Decide whether you can reliably and correctly answer the user's query.
- Choose SELF_SOLVE if you believe you can solve it by yourself.
- Choose DELEGATE if you believe it requires a more powerful model.

{output_format}

{query_section}
""".strip()


# ---------------------------------------------------------------------------
# Response templates
# ---------------------------------------------------------------------------

_RESPONSE_LABEL = """
<decision>
{decision}
</decision>
""".strip()

_RESPONSE_WITH_ANALYSIS = """
<analysis>
{analysis}
</analysis>

<decision>
{decision}
</decision>
""".strip()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_prompt_template(domain: str, sft_mode: str) -> str:
    """Build the user-turn prompt template for a given domain + sft mode."""
    if sft_mode == "label":
        output_format = _OUTPUT_FORMAT_LABEL_ONLY
    elif sft_mode in {"teacher", "self"}:
        output_format = _OUTPUT_FORMAT_WITH_ANALYSIS
    else:
        raise ValueError(
            f"Unknown sft_mode: {sft_mode!r}. Must be 'label', 'teacher', or 'self'."
        )

    if domain == "math":
        query_section = _QUERY_MATH
    elif domain == "science":
        query_section = _QUERY_SCIENCE
    else:
        raise ValueError(f"Unknown domain: {domain!r}. Must be 'math' or 'science'.")

    return _PROMPT_BODY.format(
        output_format=output_format, query_section=query_section,
    )


def get_response_template(sft_mode: str) -> str:
    """Build the assistant-turn response template for a given sft mode."""
    if sft_mode == "label":
        return _RESPONSE_LABEL
    if sft_mode in {"teacher", "self"}:
        return _RESPONSE_WITH_ANALYSIS
    raise ValueError(
        f"Unknown sft_mode: {sft_mode!r}. Must be 'label', 'teacher', or 'self'."
    )


# ---------------------------------------------------------------------------
# GRPO-time prompt (no analysis fixed in the dataset; the model produces both)
# ---------------------------------------------------------------------------

GRPO_PROMPT_TEMPLATE = _PROMPT_BODY.format(
    output_format=_OUTPUT_FORMAT_WITH_ANALYSIS,
    query_section="# Query:\n{query}",
)
